language: android
android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra


    env:
      global:
       # install timeout in minutes (2 minutes by default)
        - ADB_INSTALL_TIMEOUT=8
  